// default package
// Generated Dec 25, 2017 5:48:08 PM by Hibernate Tools 5.1.4.Final
package Model.DTO;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Food generated by hbm2java
 */
@Entity
@Table(name = "food", catalog = "restaurant")
public class Food {

	private Integer foodId;
	private String foodName;
	private Category category;
	private String image;
	private Date dateCreated;
	private Boolean flags;

	public Food() {
	}

	public Food(String foodName, Category category, String image, Date dateCreated) {
		this.foodName = foodName;
		this.category = category;
		this.image = image;
		this.dateCreated = dateCreated;
	}

	public Food(String foodName, Category category, String image, Date dateCreated, Boolean flags) {
		this.foodName = foodName;
		this.category = category;
		this.image = image;
		this.dateCreated = dateCreated;
		this.flags = flags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "foodID", unique = true, nullable = false)
	public Integer getFoodId() {
		return this.foodId;
	}

	public void setFoodId(Integer foodId) {
		this.foodId = foodId;
	}

	@Column(name = "foodName", unique = true, nullable = false, length = 100)
	public String getFoodName() {
		return this.foodName;
	}

	public void setFoodName(String foodName) {
		this.foodName = foodName;
	}

	@ManyToOne(fetch= FetchType.EAGER)
	@JoinColumn(name = "categoryId", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	
	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "image", nullable = false, length = 120)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", nullable = false, length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "flags")
	public Boolean getFlags() {
		return this.flags;
	}

	public void setFlags(Boolean flags) {
		this.flags = flags;
	}
}
