package Model.DTO;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Food generated by hbm2java
 */
@Entity
@Table(name = "food", catalog = "restaurant")
public class Food  {

	private Integer foodId;
	private String foodName;
	private int categoryId;
	private String image;
	private Boolean flags;

	public Food() {
	}


	public Food(String foodName, int categoryId, String image, Boolean flags) {
		this.foodName = foodName;
		this.categoryId = categoryId;
		this.flags = flags;
		this.image = image;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "foodID", unique = true, nullable = false)
	public Integer getFoodId() {
		return this.foodId;
	}

	public void setFoodId(Integer foodId) {
		this.foodId = foodId;
	}

	@Column(name = "foodName", nullable = false, length = 100)
	public String getFoodName() {
		return this.foodName;
	}

	public void setFoodName(String foodName) {
		this.foodName = foodName;
	}

	@Column(name = "categoryID", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}
	
	
	@Column(name = "image", nullable = false, length = 120)
	public String getImage() {
		return image;
	}


	public void setImage(String image) {
		this.image = image;
	}


	@Column(name = "flags")
	public Boolean getFlags() {
		return this.flags;
	}

	public void setFlags(Boolean flags) {
		this.flags = flags;
	}

}
