// default package
// Generated Dec 25, 2017 5:48:08 PM by Hibernate Tools 5.1.4.Final

package Model.DTO;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * MenuDepartment generated by hbm2java
 */
@Entity
@Table(name = "menu_department", catalog = "restaurant")
public class MenuDepartment  {

	private MenuDepartmentId id;
	private Department department;
	private Food food;
	private int price;
	private Date dateCreated;
	private Boolean flags;

	public MenuDepartment() {
	}

	
	public MenuDepartment(MenuDepartmentId id, int price, Date dateCreated) {
		this.id = id;
		this.price = price;
		this.dateCreated = dateCreated;
	}

	public MenuDepartment(MenuDepartmentId id, int price, Date dateCreated, Boolean flags) {
		this.id = id;
		this.price = price;
		this.dateCreated = dateCreated;
		this.flags = flags;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "departmentId", column = @Column(name = "departmentID", nullable = false)),
			@AttributeOverride(name = "foodId", column = @Column(name = "foodID", nullable = false)) })
	public MenuDepartmentId getId() {
		return this.id;
	}

	public void setId(MenuDepartmentId id) {
		this.id = id;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", nullable = false, length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "flags")
	public Boolean getFlags() {
		return this.flags;
	}

	public void setFlags(Boolean flags) {
		this.flags = flags;
	}
	

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "departmentID", nullable = false, insertable = false,  updatable = false)
	public Department getDepartment() {
		return department;
	}



	public void setDepartment(Department department) {
		this.department = department;
	}


	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "foodID", nullable = false, insertable = false,  updatable = false)
	public Food getFood() {
		return food;
	}

	public void setFood(Food food) {
		this.food = food;
	}	

}
