package Model.DTO;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MonthCost generated by hbm2java
 */
@Entity
@Table(name = "month_cost", catalog = "restaurant")
public class MonthCost  {

	private MonthCostId id;
	private String typeOfCost;
	private long price;
	private String note;
	private Boolean flags;

	public MonthCost() {
	}

	public MonthCost(MonthCostId id, long price) {
		this.id = id;
		this.price = price;
	}

	public MonthCost(MonthCostId id, String typeOfCost, long price, String note, Boolean flags) {
		this.id = id;
		this.typeOfCost = typeOfCost;
		this.price = price;
		this.note = note;
		this.flags = flags;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "departmentId", column = @Column(name = "departmentID", nullable = false)),
			@AttributeOverride(name = "monthOfCost", column = @Column(name = "monthOfCost", nullable = false, length = 10)) })
	public MonthCostId getId() {
		return this.id;
	}

	public void setId(MonthCostId id) {
		this.id = id;
	}

	@Column(name = "typeOfCost", length = 60)
	public String getTypeOfCost() {
		return this.typeOfCost;
	}

	public void setTypeOfCost(String typeOfCost) {
		this.typeOfCost = typeOfCost;
	}

	@Column(name = "price", nullable = false)
	public long getPrice() {
		return this.price;
	}

	public void setPrice(long price) {
		this.price = price;
	}

	@Column(name = "note", length = 300)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "flags")
	public Boolean getFlags() {
		return this.flags;
	}

	public void setFlags(Boolean flags) {
		this.flags = flags;
	}

}
