package Model.DTO;
// default package
// Generated Jan 2, 2018 10:02:25 AM by Hibernate Tools 5.1.4.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MonthCost generated by hbm2java
 */
@Entity
@Table(name = "month_cost", catalog = "restaurant")
public class MonthCost implements java.io.Serializable {

	private Integer monthCostId;
	private int departmentId;
	private String monthOfCost;
	private String typeOfCost;
	private int price;
	private String note;
	private Date dateCreated;
	private boolean flags;

	public MonthCost() {
	}

	public MonthCost(int departmentId, String monthOfCost, String typeOfCost, int price, Date dateCreated,
			boolean flags) {
		this.departmentId = departmentId;
		this.monthOfCost = monthOfCost;
		this.typeOfCost = typeOfCost;
		this.price = price;
		this.dateCreated = dateCreated;
		this.flags = flags;
	}

	public MonthCost(int departmentId, String monthOfCost, String typeOfCost, int price, String note, Date dateCreated,
			boolean flags) {
		this.departmentId = departmentId;
		this.monthOfCost = monthOfCost;
		this.typeOfCost = typeOfCost;
		this.price = price;
		this.note = note;
		this.dateCreated = dateCreated;
		this.flags = flags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "monthCostId", unique = true, nullable = false)
	public Integer getMonthCostId() {
		return this.monthCostId;
	}

	public void setMonthCostId(Integer monthCostId) {
		this.monthCostId = monthCostId;
	}

	@Column(name = "departmentId", nullable = false)
	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "monthOfCost", nullable = false, length = 8)
	public String getMonthOfCost() {
		return this.monthOfCost;
	}

	public void setMonthOfCost(String monthOfCost) {
		this.monthOfCost = monthOfCost;
	}

	@Column(name = "typeOfCost", nullable = false, length = 100)
	public String getTypeOfCost() {
		return this.typeOfCost;
	}

	public void setTypeOfCost(String typeOfCost) {
		this.typeOfCost = typeOfCost;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", nullable = false, length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "flags", nullable = false)
	public boolean isFlags() {
		return this.flags;
	}

	public void setFlags(boolean flags) {
		this.flags = flags;
	}

}
