package Model.DTO;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RestaurantTable generated by hbm2java
 */
@Entity
@Table(name = "restaurant_table", catalog = "restaurant")
public class RestaurantTable {

	private Integer tableId;
	private int tableNumber;
	private String tableStatus;
	private int departmentId;
	private Boolean flags;

	public RestaurantTable() {
	}

	public RestaurantTable(int tableNumber, String tableStatus, int departmentId) {
		this.tableNumber = tableNumber;
		this.tableStatus = tableStatus;
		this.departmentId = departmentId;
	}

	public RestaurantTable(int tableNumber, String tableStatus, int departmentId, Boolean flags) {
		this.tableNumber = tableNumber;
		this.tableStatus = tableStatus;
		this.departmentId = departmentId;
		this.flags = flags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tableID", unique = true, nullable = false)
	public Integer getTableId() {
		return this.tableId;
	}

	public void setTableId(Integer tableId) {
		this.tableId = tableId;
	}

	@Column(name = "tableNumber", nullable = false)
	public int getTableNumber() {
		return this.tableNumber;
	}

	public void setTableNumber(int tableNumber) {
		this.tableNumber = tableNumber;
	}

	@Column(name = "tableStatus", nullable = false, length = 7)
	public String getTableStatus() {
		return this.tableStatus;
	}

	public void setTableStatus(String tableStatus) {
		this.tableStatus = tableStatus;
	}

	@Column(name = "departmentID", nullable = false)
	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "flags")
	public Boolean getFlags() {
		return this.flags;
	}

	public void setFlags(Boolean flags) {
		this.flags = flags;
	}

}
