package Model.DTO;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name = "staff", catalog = "restaurant")
public class Staff {

	private Integer staffId;
	private String staffName;
	private String address;
	private String phoneNumber;
	private String staffType;
	private int salary;
	private int departmentId;
	private Boolean flags;

	public Staff() {
	}

	public Staff(String staffName, String address, String phoneNumber, String staffType, int salary, int departmentId) {
		this.staffName = staffName;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.staffType = staffType;
		this.salary = salary;
		this.departmentId = departmentId;
	}

	public Staff(String staffName, String address, String phoneNumber, String staffType, int salary, int departmentId,
			Boolean flags) {
		this.staffName = staffName;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.staffType = staffType;
		this.salary = salary;
		this.departmentId = departmentId;
		this.flags = flags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "staffID", unique = true, nullable = false)
	public Integer getStaffId() {
		return this.staffId;
	}

	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	@Column(name = "staffName", nullable = false, length = 100)
	public String getStaffName() {
		return this.staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	@Column(name = "address", nullable = false, length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phoneNumber", nullable = false, length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "staffType", nullable = false, length = 50)
	public String getStaffType() {
		return this.staffType;
	}

	public void setStaffType(String staffType) {
		this.staffType = staffType;
	}

	@Column(name = "salary", nullable = false)
	public int getSalary() {
		return this.salary;
	}

	public void setSalary(int salary) {
		this.salary = salary;
	}

	@Column(name = "departmentID", nullable = false)
	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "flags")
	public Boolean getFlags() {
		return this.flags;
	}

	public void setFlags(Boolean flags) {
		this.flags = flags;
	}

}
