// default package
// Generated Dec 25, 2017 5:48:08 PM by Hibernate Tools 5.1.4.Final

package Model.DTO;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DateCostId generated by hbm2java
 */
@Embeddable
public class DateCostId implements java.io.Serializable {

	private int departmentId;
	private Date dateOfCost;

	public DateCostId() {
	}

	public DateCostId(int departmentId, Date dateOfCost) {
		this.departmentId = departmentId;
		this.dateOfCost = dateOfCost;
	}

	@Column(name = "departmentID", nullable = false)
	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "dateOfCost", nullable = false, length = 10)
	public Date getDateOfCost() {
		return this.dateOfCost;
	}

	public void setDateOfCost(Date dateOfCost) {
		this.dateOfCost = dateOfCost;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DateCostId))
			return false;
		DateCostId castOther = (DateCostId) other;

		return (this.getDepartmentId() == castOther.getDepartmentId())
				&& ((this.getDateOfCost() == castOther.getDateOfCost())
						|| (this.getDateOfCost() != null && castOther.getDateOfCost() != null
								&& this.getDateOfCost().equals(castOther.getDateOfCost())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDepartmentId();
		result = 37 * result + (getDateOfCost() == null ? 0 : this.getDateOfCost().hashCode());
		return result;
	}

}
