<<<<<<< HEAD
package Model.DTO;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;


/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = "restaurant")
public class Department {

	private Integer departmentId;
	private String departmentName;
	private String address;
	private String phoneNumber;
	private short numberOfTable;
	private Boolean flags;
	
	@JsonIgnore 
	private Set<MenuDepartment> menuDepartments = new HashSet<MenuDepartment>(0);

	public Department() {
	}

	public Department(String departmentName, String address, String phoneNumber, short numberOfTable) {
		this.departmentName = departmentName;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.numberOfTable = numberOfTable;
	}

	public Department(String departmentName, String address, String phoneNumber, short numberOfTable, Boolean flags) {
		this.departmentName = departmentName;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.numberOfTable = numberOfTable;
		this.flags = flags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "departmentID", unique = true, nullable = false)
	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "departmentName", nullable = false, length = 100)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	@Column(name = "address", nullable = false, length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phoneNumber", nullable = false, length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "numberOfTable", nullable = false)
	public short getNumberOfTable() {
		return this.numberOfTable;
	}

	public void setNumberOfTable(short numberOfTable) {
		this.numberOfTable = numberOfTable;
	}

	@Column(name = "flags")
	public Boolean getFlags() {
		return this.flags;
	}

	public void setFlags(Boolean flags) {
		this.flags = flags;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<MenuDepartment> getMenuDepartments() {
		return this.menuDepartments;
	}

	public void setMenuDepartments(Set<MenuDepartment> menuDepartments) {
		this.menuDepartments = menuDepartments;
	}

}
=======
package Model.DTO;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;


/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = "restaurant")
public class Department {

	private Integer departmentId;
	private String departmentName;
	private String address;
	private String phoneNumber;
	private short numberOfTable;
	private Boolean flags;
	
	@JsonIgnore 
	private Set<MenuDepartment> menuDepartments = new HashSet<MenuDepartment>(0);

	public Department() {
	}

	public Department(String departmentName, String address, String phoneNumber, short numberOfTable) {
		this.departmentName = departmentName;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.numberOfTable = numberOfTable;
	}

	public Department(String departmentName, String address, String phoneNumber, short numberOfTable, Boolean flags) {
		this.departmentName = departmentName;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.numberOfTable = numberOfTable;
		this.flags = flags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "departmentID", unique = true, nullable = false)
	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "departmentName", nullable = false, length = 100)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	@Column(name = "address", nullable = false, length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phoneNumber", nullable = false, length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "numberOfTable", nullable = false)
	public short getNumberOfTable() {
		return this.numberOfTable;
	}

	public void setNumberOfTable(short numberOfTable) {
		this.numberOfTable = numberOfTable;
	}

	@Column(name = "flags")
	public Boolean getFlags() {
		return this.flags;
	}

	public void setFlags(Boolean flags) {
		this.flags = flags;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<MenuDepartment> getMenuDepartments() {
		return this.menuDepartments;
	}

	public void setMenuDepartments(Set<MenuDepartment> menuDepartments) {
		this.menuDepartments = menuDepartments;
	}

}
>>>>>>> refs/remotes/origin/1412163
