package Model.DTO;
// Generated Nov 8, 2017 7:11:15 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Food generated by hbm2java
 */
@Entity
@Table(name = "food", catalog = "restaurant")
public class Food implements java.io.Serializable {

	private Integer foodId;
	private String foodName;
	private int categoryId;
	private Boolean flags;

	public Food() {
	}

	public Food(String foodName, int categoryId) {
		this.foodName = foodName;
		this.categoryId = categoryId;
	}

	public Food(String foodName, int categoryId, Boolean flags) {
		this.foodName = foodName;
		this.categoryId = categoryId;
		this.flags = flags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "foodID", unique = true, nullable = false)
	public Integer getFoodId() {
		return this.foodId;
	}

	public void setFoodId(Integer foodId) {
		this.foodId = foodId;
	}

	@Column(name = "foodName", nullable = false, length = 100)
	public String getFoodName() {
		return this.foodName;
	}

	public void setFoodName(String foodName) {
		this.foodName = foodName;
	}

	@Column(name = "categoryID", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "flags")
	public Boolean getFlags() {
		return this.flags;
	}

	public void setFlags(Boolean flags) {
		this.flags = flags;
	}

}
