package Model.DTO;
// Generated Nov 8, 2017 7:11:15 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MenuDepartment generated by hbm2java
 */
@Entity
@Table(name = "menu_department", catalog = "restaurant")
public class MenuDepartment implements java.io.Serializable {

	private MenuDepartmentId id;
	private int price;
	private Boolean flags;

	public MenuDepartment() {
	}

	public MenuDepartment(MenuDepartmentId id, int price) {
		this.id = id;
		this.price = price;
	}

	public MenuDepartment(MenuDepartmentId id, int price, Boolean flags) {
		this.id = id;
		this.price = price;
		this.flags = flags;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "departmentId", column = @Column(name = "departmentID", nullable = false)),
			@AttributeOverride(name = "foodId", column = @Column(name = "foodID", nullable = false)) })
	public MenuDepartmentId getId() {
		return this.id;
	}

	public void setId(MenuDepartmentId id) {
		this.id = id;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Column(name = "flags")
	public Boolean getFlags() {
		return this.flags;
	}

	public void setFlags(Boolean flags) {
		this.flags = flags;
	}

}
