// default package
// Generated Dec 25, 2017 5:48:08 PM by Hibernate Tools 5.1.4.Final

package Model.DTO;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MonthCost generated by hbm2java
 */
@Entity
@Table(name = "month_cost", catalog = "restaurant")
public class MonthCost  {

	private MonthCostId id;
	private String typeOfCost;
	private long price;
	private String note;
	private Date dateCreated;
	private Boolean flags;

	public MonthCost() {
	}

	public MonthCost(MonthCostId id, long price, Date dateCreated) {
		this.id = id;
		this.price = price;
		this.dateCreated = dateCreated;
	}

	public MonthCost(MonthCostId id, String typeOfCost, long price, String note, Date dateCreated, Boolean flags) {
		this.id = id;
		this.typeOfCost = typeOfCost;
		this.price = price;
		this.note = note;
		this.dateCreated = dateCreated;
		this.flags = flags;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "departmentId", column = @Column(name = "departmentID", nullable = false)),
			@AttributeOverride(name = "monthOfCost", column = @Column(name = "monthOfCost", nullable = false, length = 10)) })
	public MonthCostId getId() {
		return this.id;
	}

	public void setId(MonthCostId id) {
		this.id = id;
	}

	@Column(name = "typeOfCost", length = 60)
	public String getTypeOfCost() {
		return this.typeOfCost;
	}

	public void setTypeOfCost(String typeOfCost) {
		this.typeOfCost = typeOfCost;
	}

	@Column(name = "price", nullable = false)
	public long getPrice() {
		return this.price;
	}

	public void setPrice(long price) {
		this.price = price;
	}

	@Column(name = "note", length = 300)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", nullable = false, length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "flags")
	public Boolean getFlags() {
		return this.flags;
	}

	public void setFlags(Boolean flags) {
		this.flags = flags;
	}

}
