// default package
// Generated Dec 25, 2017 5:48:08 PM by Hibernate Tools 5.1.4.Final
package Model.DTO;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MonthCostId generated by hbm2java
 */
@Embeddable
public class MonthCostId implements java.io.Serializable {

	private int departmentId;
	private String monthOfCost;

	public MonthCostId() {
	}

	public MonthCostId(int departmentId, String monthOfCost) {
		this.departmentId = departmentId;
		this.monthOfCost = monthOfCost;
	}

	@Column(name = "departmentID", nullable = false)
	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "monthOfCost", nullable = false, length = 10)
	public String getMonthOfCost() {
		return this.monthOfCost;
	}

	public void setMonthOfCost(String monthOfCost) {
		this.monthOfCost = monthOfCost;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MonthCostId))
			return false;
		MonthCostId castOther = (MonthCostId) other;

		return (this.getDepartmentId() == castOther.getDepartmentId())
				&& ((this.getMonthOfCost() == castOther.getMonthOfCost())
						|| (this.getMonthOfCost() != null && castOther.getMonthOfCost() != null
								&& this.getMonthOfCost().equals(castOther.getMonthOfCost())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDepartmentId();
		result = 37 * result + (getMonthOfCost() == null ? 0 : this.getMonthOfCost().hashCode());
		return result;
	}

}
